### ISSUE TITLE
Why does the pytorch version not have transform？

### ISSUE THREAD

**Issue by sahalaan** [WangYueFt/dgcnn#77] opened 2021-06-10 09:44 UTC
I cannot find the transform in pytorch version but can find it in tensorflow version. Can somebody find and note where the trasform in pytorch version is?  Thank you very much.

**Comment by bramton** [comment] 2022-05-19 07:28
Duplicate of #32 

This repo has a nice PyTorch implementation of the spatial transform: https://github.com/AnTao97/dgcnn.pytorch

**Comment by sahalaan** [comment] 2022-05-20 03:06
Accurate and perfect. Thank you!

**Comment by sahalaan** [comment] 2022-05-20 03:06
> 

Accurate and perfect. Thank you!

**Closed as completed** 2022-05-20 03:07 UTC
